### ISSUE TITLE
Mac: Resize breaks TUI on MacOS

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#12]
Originally filed November 27 2021 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/96)

I tried resizing the window and the TUI got stuck in an unresponsive state

![image](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/uploads/1d4aa5f81390f9d50881f943c2294dc7/image.png)

**Comment by rmadsen-ks** [comment]
Moving this out of the milestone as it only affects MacOS.

**Comment by alnlarsen** [comment]
@rmadsen-ks this also doesn't work for me in Linux

**Comment by alnlarsen** [comment]
I tried rebasing the latest release of gui.cs, and it doesn't seem to fix resizing, at least on Linux.
