### ISSUE TITLE
Remember settings window state when changing steps

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#14]
Originally filed November 28 2021 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/99)

It would be nice if the TUI remembered what groups are expanded / collapsed when changing steps.

Currently, when switching between two steps, it remembers what groups are open by name.
For example. if the 'common' group is open on one step, it will remain open when changing steps.

It would be much nicer if this was remembered per step, as the current behavior is a bit weird.

**Comment by frederikja163** [comment]
Closing as this was fixed in #42
