### ISSUE TITLE
Exploding newlines in multi-line editor

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#15]
Originally filed January 28 2022 by Rolf Madsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/105)

It seems that when editing an element that contains multiple lines, whenever exiting the edit mode, the newlines gets multiplied.

**Comment by frederikja163** [comment]
Cant reproduce on master
