### ISSUE TITLE
Edit provider for datetime

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#18]
Originally filed February 18 2022 by Stefan Holst on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/108)

**Comment by alnlarsen** [comment]
@StefanHolst do you mean like a TUI calendar where you can scroll through months and years to pick a date?

**Comment by StefanHolst** [comment]
@alnlarsen That would be cool, but no I think my issue was just i could not chang any datetime property.
