### ISSUE TITLE
Allow moving the focus to the log panel

### ISSUE THREAD

**Issue by rmadsen-ks** [StefanHolst/opentap-tui#38]
Currently the only way I can move the focus to the log panel is by clicking it with the mouse. This is very counter intuitive for a console application.

If tab could move the focus there, shift+tab could move the focus back as well.

**Comment by frederikja163** [comment]
You can select the log panel by clicking F4, however i think this issue shows a more general problem with the TUI. Unintuitive shortcuts all over the place, and these shortcuts being the best way to do things.

A few other examples of this come to mind immediately:
 - Tab to move between views
 - F7 to select the top toolbar
 - Space to move steps around
 - Escape to exit some menus
 - Space to toggle boolean properties, but only after opening the property editor with enter

**Comment by frederikja163** [comment]
Closing as this is a non issue after making a help menu #43
