### ISSUE TITLE
Implement Ranger-like file explorer

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#4]
Originally filed January 08 2020 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/18)

https://github.com/ranger/ranger

Ranger is a terminal based file manager for linux. A similar design would provide a much clearer overview for saving and opening files, and previewing text files

![Rangerdemo](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/uploads/8e02ee209efbb7b48a428831ded245aa/Rangerdemo.gif)

**Comment by frederikja163** [comment]
Cool idea, if you want to implement it we can take a look at it.
