### ISSUE TITLE
Error dialog doesn't wrap text

### ISSUE THREAD

**Issue by alnlarsen** [StefanHolst/opentap-tui#45]
When a test plan loads with errors, the text box doesn't use wrapping

![image](https://user-images.githubusercontent.com/95965749/178964668-c457a953-4e86-4fd4-ac7b-4b2ed5b7a04d.png)

**Comment by frederikja163** [comment]
This is by design as the dialog opens up as a properties view to enable complex input. You can click on the text to open the text in a full view.
