### ISSUE TITLE
Linux: Keyboard shortcuts for menus are not working

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#6]
Originally filed January 29 2020 by Sebastian Vlaic on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/34)

**Setup**
* Ubuntu 19.04 VM
* OpenTAP 9.5.1
* TUI 0.1.0-beta38

**Steps:**
Opening menus with Alt +F/E/S does not work

Menus can be opened using F9 though

**Comment by frederikja163** [comment]
Closing as this feature has been disabled
