### ISSUE TITLE
Common / Enabled can be changed after is parameterized

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#88]
**Environment**

Windows 10, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Add a **Delay** step
* 2. Go to **F7 Settings** panel
* 3. Parameterize the **Common / Enabled** option 
* 4. Edit the setting without unparameterizing it

**Actual result:**

You can enable - disable the option after you parameterize

**Comment by frederikja163** [comment]
Not sure if this is an issue @rmadsen-ks
