### ISSUE TITLE
Mac: Menu bindings do not work on mac

### ISSUE THREAD

**Issue by StefanHolst** [StefanHolst/opentap-tui#9]
Originally filed August 11 2021 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/Plugins/keysight/opentap-tui/-/issues/87)

On windows, you can press Alt+E to open the Edit menu, but Option+E on Mac just inserts symbols. It would be nice to support something similar on Mac.

**Comment by frederikja163** [comment]
Closing as this feature has been removed.

There is a problem with recognising any Alt/Option keys in the NCurses library used by guics. Maybe this issue is worth investigating? We have also talked about creating our own guics from scratch which would then be able to solve this issue.
