### ISSUE TITLE
Disabling the Common option will still give you the option to RUN the test plan

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#91]
**Environment**

Windows 10, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Add a **Delay** step
* 2. Go to **F7 Settings** panel
* 3. Disable the  **Common** option 
* 4. Press **F5 Run Test Plan**

**Actual result:**

You can RUN a test plan with **Common** option disabled

**Comment by frederikja163** [comment]
Not sure what you expected to happen here, or if there is a bug here at all. Maybe @rmadsen-ks can weigh in?

**Comment by frederikja163** [comment]
This is expected behaviour
