### ISSUE TITLE
Adding a new step using F2 key will crush TUI on macOS

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#95]
**Environment**

macOS v12.6, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Open TUI
* 2. Add a new step using **F2**

**Actual result:**

Adding a new step using **F2** key will crush the app

![2022-10-05 09 07 10](https://user-images.githubusercontent.com/110477118/194001868-0ad2dc23-4d01-4fc6-ae20-7fd4829a050c.gif)

**Comment by frederikja163** [comment]
Can you provide the session logs for when this happens?

**Comment by rmadsen-ks** [comment]
I also cannot reproduce this on MacOS.
