### ISSUE TITLE
You can RUN a test plan with a Succesfull message without adding any steps

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#96]
**Environment**

macOS v12.6, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Open **TUI**
* 2. Press **F5** key for running a test plan without adding any steps

**Actual result:**

Actually, you get a successful message: **Test Plan completed successfully**

![2022-10-05 12 37 05](https://user-images.githubusercontent.com/110477118/194041645-677b61cd-f4af-410e-9f23-ea2625b67c76.gif)

**Comment by rmadsen-ks** [comment]
I think this is fine. There is nothing in OpenTAP preventing the user from running an empty test plan.

**Comment by frederikja163** [comment]
Closing as this is expected behaviour
