### ISSUE TITLE
TUI crashes when you go to Package Manager and scroll down to Demonstration

### ISSUE THREAD

**Issue by apantir** [StefanHolst/opentap-tui#99]
**Environment**

Windows 10, 64-bit
OpenTAP v9.19.0+22538968
TUI 1.0.0-rc+cfb8eede

**Steps to reproduce:**

* 1. Go to **Tools** > **Package Manager**
* 2. Scroll down with the directional key until reaching the **Demonstration**

**Actual result:**

TUI exits

**Comment by rmadsen-ks** [comment]
I also cannot reproduce this issue. Closing for new.
